# 设置springboot web服务启动的默认端口
server:
  port: 9090
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/hellospringboot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

##    用过hibernate的同学知道 hibernate可以通过实体类逆向创建表，只需要配置一下ddl-auto 就可以
#  jpa:
#    hibernate:
##      第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），以后加载hibernate时根据 model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行
#      ddl-auto: update
##      表示会在日志中打印我们操作的sql
#    show-sql: true


#    mybatis 的配置 可以和上面的jpa二选一；如果使用mybatis，则去掉jpa的依赖，并注释掉UserRepository接口和重写UserService业务层
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml #配置mapper.xml位置，文件放置在/src/main/resource/mybatis/mapper目录下
  config-location: classpath:/mybatis/config/mybatis-config.xml #是配置mybatis-config.xml的位置，文件放置在/src/main/resource/mybatis/config目录下


